name: Run Python script
on:
  schedule:
    - cron: '0 * * * *'   # 每小时运行一次
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.4'
      - run: pip install -r requirements.txt
      - run: python bot.py
