name: Run Discord Bot

on:
  schedule:
    - cron: '21 21 * * *'   # 06:00 JST = 21:00 UTC 前一天
    - cron: '3 3 * * *'     # 12:00 JST = 03:00 UTC
    - cron: '9 9 * * *'     # 18:00 JST = 09:00 UTC
    - cron: '15 15 * * *'   # 24:00 JST = 15:00 UTC
  workflow_dispatch:        # 手动触发也保留

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libopus0
          pip install -r requirements.txt
          
      - name: Run bot
        run: python bot.py
