name: Schedule & Dispatch Bot Run

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs of 'Run Discord Bot'
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: 'run.yml'  # 或者使用数字ID，如 179498731（你的run.yml workflow的ID）
          token: ${{ secrets.PAT_TOKEN }}

  dispatch-new:
    needs: cancel-previous
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Run Discord Bot workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run.yml
          token: ${{ secrets.PAT_TOKEN }}
