name: Schedule & Dispatch Bot Run

on:
  schedule:
    # 每天 0, 6, 12, 18 点触发
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs of 'Run Discord Bot'
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: 'run.yml' # 你主 workflow 的文件名
          token: ${{ secrets.PAT_TOKEN }}

  dispatch-new:
    needs: cancel-previous
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Run Discord Bot workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run.yml
          token: ${{ secrets.PAT_TOKEN }}
